WITH customers AS (
  SELECT ID, WEBSITE, ACTIVE FROM "BRIAN_KRANSON"."SQL_SERVER_DEMO_DBO"."ACCOUNT"
  WHERE _FIVETRAN_DELETED = FALSE
  AND ACITVE = 1
  ORDER BY WEBSITE DESC
),

final AS (
  SELECT * FROM customers
)

SELECT * FROM final
